name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@v6
